### ISSUE TITLE
add example for new UCSX direct (UCSX-S9108-G100) 

### ISSUE THREAD

**Issue by ViciousSquirrel** [terraform-cisco-modules/easy-imm#2]
can we get an example (Hordefrost) of a setup using the new UCSX mini

basic config port 7/8 as 10G uplink with PC ports
iSCSI attached storage on port 1/2 

also would like to see a better example of doing break out for uplinks QSFP to 4X 10G FTP+ 

I am new to this so might have missed it 1st look through - and could find another way to ask for help

**Comment by scotttyso** [comment]
@ViciousSquirrel 

The port-policy is the only difference for X-Direct.

Example shown here
https://github.com/terraform-cisco-modules/easy-imm/blob/main/policies/port.ezi.yaml

Note that because iSCSI would be a different VLAN For fabric A and Fabric B, the port-policy can't be combined like the Fibre-Channel examples.  That is because you need a difference VLAN group (ethernet network group policy) for each fabric for iSCSI.

So take note how the x-direct example has one entry for ```ucsx-direct-example-a``` and another entry for ```ucsx-direct-example-b```.

**Comment by scotttyso** [comment]
@ViciousSquirrel - Additionally, if you add the JSON Schema to Visual Studio Code, the help context will guide you through any scenario's I have not covered in the examples in the repository.

**Comment by ViciousSquirrel** [comment]
thanks that helped a lot.

**Comment by scotttyso** [comment]
you're welcome
